name: CI for flask-app

on: 
  push:
    branches: main
  pull_request:
    branches: main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build docker image
        run: |
          cd python/flask-app
          docker build -t flask-app .

      - name: Run docker
        run: |
          cd python/flask-app
          docker run -d -p 5000:5000 --name flask-app-container flask-app
