name: Wanderlust CI/CD
on: 
   # push: 
   #   branches: main
  #   paths-ignore:
  #     - './.github/workflows/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  run-reusable-workflow:
    name: "Wanderlust CI"
    uses: dhruv-development/reusable_workflows/.github/workflows/wanderlust-ci.yml@main
    with:
      role-assume: "arn:aws:iam::410454990341:role/GitHubActionsRole"
      AWS_REGION: "us-east-2"
      ECR_BACKEND_REPO: "dev-backend"
      ECR_FRONTEND_REPO: "dev-frontend"
      BACKEND_TASK_DEFINITION: "Wanderlust-task-backend"
      FRONTEND_TASK_DEFINITION: "Wanderlust-task-frontend"
      BACKEND_SERVICE: "Wanderlust-service-backend"
      FRONTEND_SERVICE: "Wanderlust-service-frontend"
      CLUSTER: "Wanderlust"
